imxrt-rs/imxrt-hal

- imxrt-hal/Cargo.toml
- imxrt-hal/src/ccm.rs
- imxrt-hal/src/ccm/arm_clock.rs
- imxrt-hal/src/gpio.rs
- imxrt-hal/src/iomuxc.rs
- imxrt-hal/src/iomuxc/gpio/ad_b0.rs
- imxrt-hal/src/iomuxc/gpio/ad_b1.rs
- imxrt-hal/src/iomuxc/gpio/b0.rs
- imxrt-hal/src/iomuxc/gpio/b1.rs
- imxrt-hal/src/iomuxc/gpio/emc.rs
- imxrt-hal/src/iomuxc/gpio/sd_b0.rs
- imxrt-hal/src/iomuxc/macros.rs
- imxrt-hal/src/lib.rs
Note that each pad requires unsafe modify_reg() calls to convert to a
particular pads alternate usage.
This should be safe because each pad has its own register pair (mux/pad) for
setting things up. So long as the only place where these registers are
used is in the iomuxc instance in struct Peripherals, this is like just
fine.
I'm not excited to have to import the modify_reg!() macro in each gpio module, I didn't try using it using crate::ral::modify_reg!() which perhaps works already, will try later perhaps.
> Port iomux to imxrt-ral

- imxrt-hal/src/lib.rs
- imxrt-hal/src/pit.rs
The PIT timers needed some internal changes to support the lack of register clustering in the RAL. We extend the existing `Channel` trait to provide implementations of the register manipulations that we need. We then call onto those trait methods in the `PIT` implementation. We should check the port for consistency.
> Port PIT timers

- imxrt-ral/imxrtral.py
Adds #[repr(C)] to RegisterBlock structs to ensure memory alignment
Based on #16 
Fixes #13
> Imxrt ral repr c

- imxrt-hal/src/gpio.rs
- imxrt-hal/src/iomuxc.rs
- imxrt-hal/src/iomuxc/gpio.rs
- imxrt-hal/src/iomuxc/gpio/ad_b1.rs
- imxrt-hal/src/iomuxc/gpio/b0.rs
- imxrt-hal/src/iomuxc/gpio/emc.rs
- imxrt-hal/src/iomuxc/gpio/sd_b0.rs
- imxrt-hal/src/iomuxc/gpio/sd_b1.rs
The PR ports GPIO additions from the `teensy4-rs` project. In mciantyre/teensy4-rs#47, we added additional GPIOs to support SPI master devices. This PR accounts for part of #9.
I'm targeting the existing `hal_gpio` branch. If accepted, we can add the safety as discussed in #22 in `hal_gpio`, then merge everything into `master`.
> Port remaining GPIOs from teensy4-rs

- imxrt-hal/src/ccm.rs
I was finishing the rounds of hardware testing on the Teensy 4, and I found that timings based on PITs were wrong. I tracked it down to the CCM module, and how we modify the PIT peripheral's clock inputs.
The commit updates the modify_reg! call to set the divider as part of the periodic clock configuration flow.
> Write periodic clock divider to CSCMR1

- .github/workflows/rust.yml
- imxrt-hal/src/gpio.rs
- imxrt-hal/src/i2c.rs
- imxrt-ral/imxrtral.py
The PR enables `clippy` in CI. It asserts that there are no `clippy` warnings or errors in the HAL. The PR also cleans up existing `clippy` warnings.
#34 added automated builds and code formatting checks. It did not include a check for `clippy` issues. #35 notes that we can't immediately use the `actions-rs/clippy` GitHub action, since we don't have a working directory for the RAL. I propose that we run `clippy` even if we cannot realize the output in a GitHub UI. The output provided by the job is still actionable.
I structured the commits to show that [the CI flow will catch clippy issues in the HAL](https://github.com/mciantyre/imxrt-rs/runs/543625866).
Closes #35.
> Enable clippy in CI

- imxrt-hal/src/iomuxc.rs
- imxrt-hal/src/iomuxc/gpio/ad_b0.rs
- imxrt-hal/src/iomuxc/gpio/ad_b1.rs
- imxrt-hal/src/iomuxc/gpio/b0.rs
- imxrt-hal/src/iomuxc/gpio/b1.rs
- imxrt-hal/src/iomuxc/gpio/emc.rs
- imxrt-hal/src/iomuxc/gpio/sd_b0.rs
- imxrt-hal/src/iomuxc/gpio/sd_b1.rs
- imxrt-hal/src/iomuxc/macros.rs
- imxrt-hal/src/iomuxc/pin_config.rs
Adds a pin configuration struct and set of builder like functions
for it. Easily used with const values or at run time with the
builder pattern if needed. Every pad!() macro call now needs to pass its PAD_CTL_PAD related register in
> Pin configuration and builder

- imxrt-hal/src/gpio.rs
- imxrt-hal/src/iomuxc.rs
Adds some needed pad definitions to make the 1060evk arduino header usable.
Depends on the pin_config branch being merged first
> EVK1060 Pads

- imxrt-hal/src/uart.rs
Copied from I2C's error type, without `Copy` as this error is more complex. Both `ReadErrorFlags` and `u8` are `Copy`, though, if that's desired.
> Add derives for UART ReadError

- imxrt-hal/CHANGELOG.md
- imxrt-hal/src/ccm.rs
- imxrt-hal/src/gpt.rs
- imxrt-hal/src/lib.rs
- imxrt-hal/src/pit.rs
The PR adds general purpose timers (GPT) to the HAL. They're similar to the periodic interrupt timers (PIT), but more general. Users can also support multiple timers from a single GPT instance, rather than having multiple PIT objects to manage. `GPT`s implement the traits of the `embedded_hal::timer` module. The GPTs are nifty if you need a counter that wraps around; PITs don't support wrap-around.
The PR introduces a breaking change in the way we configure PIT clocks. I've described the change in the HAL's new changelog.
There's GPT examples in the `teensy4-rs` project.
- `gpt.rs` shows how we can [use a `GPT` to generate interrupts](https://github.com/mciantyre/teensy4-rs/blob/c46be85d8a636337e360c3e05e55b7b8af5834d8/teensy4-examples/src/gpt.rs)
- The updated `timer.rs` shows how to …
> Add general purpose timers

- README.md
Suggestion: add development instructions in the readme, to make contributing easier.
Let me know if there's more steps required!
Before running these steps, I wasn't able to run `cargo check` in the workspace:
```
cargo check
error: failed to read `/Users/walther/git/imxrt-rs/imxrt-ral/Cargo.toml`
Caused by:
No such file or directory (os error 2)
```
After these steps, I can run `cargo check`, but I get 8324 errors 😅 
[errors.txt](https://github.com/imxrt-rs/imxrt-rs/files/4533768/errors.txt)
```
error: aborting due to 8324 previous errors
Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `imxrt-hal`.
```
> Add development instructions to Readme

- .github/workflows/rust.yml
- imxrt-ral/imxrtral.py
The PR addresses issues with our CI builds. We excluded the RAL's `Cargo.toml` in #45, and we seem to regularly see CI build failures after that PR. The errors indicate that the system [can't find the RAL's `Cargo.toml`](https://github.com/imxrt-rs/imxrt-rs/runs/618287558), which we were expecting to be in VCS (example error in #51).
We now cache the entire `imxrt-ral` directory, not just the `imxrt-ral/src` Rust source files. This includes the RAL's `Cargo.toml` in the cache.
I also swapped some build steps. If we have a cache hit, we don't need to install the Python dependencies and set up the Python environments, since they're only necessary to build the RAL. It lets us skip two more steps for each cache hit.
> Fix CI builds

- imxrt-hal/Cargo.toml
- imxrt-hal/src/gpt.rs
- imxrt-hal/src/i2c.rs
- imxrt-hal/src/iomuxc.rs
- imxrt-hal/src/iomuxc/macros.rs
- imxrt-hal/src/iomuxc/pin_config.rs
- imxrt-hal/src/pit.rs
- imxrt-hal/src/pwm.rs
- imxrt-hal/src/spi.rs
- imxrt-hal/src/uart.rs
Keeping on my documentation kick, the PR adds module-level examples for almost all of the peripherals. `cargo test` will make sure that all of these examples compile. I derived them from the Teensy 4 examples.
I'm also including a fix to the HAL's `Cargo.toml`. The HAL's documentation [fails to build on docs.rs](https://docs.rs/crate/imxrt-hal/0.2.1/builds). We specify a feature-flag to use when generating the docs, which should fix the doc build. I tested it locally, but we'll know if it works the next time we release the HAL.
> Add module-level, compiler-checked examples

- .github/workflows/rust.yml
- imxrt-ral/CHANGELOG.md
- imxrt-ral/README.md
- imxrt-ral/imxrtral.py
- imxrt-ral/src/register.rs
The PR provides some RAL touch-ups:
- Fixes the RAL documentation examples to use the `imxrt_ral` crate. Closes #36.
- Test the RAL documentation when testing the RALs in CI.
- Update the RAL's CHANGELOG.
Leave a note if you'd like the time to review. Otherwise, I'll merge this PR within the next few days.
> Fix doctests in the RAL

- imxrt-hal/CHANGELOG.md
- imxrt-hal/src/dma/peripheral.rs
- imxrt-hal/src/iomuxc/uart.rs
- imxrt-hal/src/uart.rs
I'm thinking about adding a new, UART-based logging back-end for the Teensy. Logging might only need the transfer half of a UART peripheral. This PR proposes split-able UART peripherals.
Users can `split()` a peripheral into transfer and receive halves. The transfer half only supports writes; the receive half, only reads. Users can `join()` the halves if they need to re-configure the
peripheral. The two halves implement the DMA's `Source` and `Destination` traits, so they may serve as uni-directional DMA sources and destinations.
Tested in the Teensy 4 repo, at [aca5424](https://github.com/mciantyre/teensy4-rs/commit/aca5424ea07cfe1421362cc7dd6a6912b5dad6a2).
> Support split UART peripherals

- imxrt-ral/imxrtral.py
The PR proposes that all RAL instances are `Send`. `Send`-able `Instance`s are [feature-gated behind `"rtfm"`](https://docs.rs/imxrt-ral/0.2.1/src/imxrt_ral/imxrt106/peripherals/lpi2c.rs.html#2704), but it seems like a useful feature for non-RTFM users.
By enabling `Send` for RAL instances, most HAL peripherals will also become `Send`. We can then wrap HAL peripherals in `Sync`-able [`cortex_m::interrupt::Mutex`es](https://docs.rs/cortex-m/0.6.2/cortex_m/interrupt/struct.Mutex.html), or use them wherever else `Send` is necessary.
`Send`-able RAL instances would match what `svd2rust` outputs ([sample](https://docs.rs/stm32f0/0.11.0/src/stm32f0/stm32f0x8/mod.rs.html#417) of an `svd2rust` output). Both RAL and `svd2rust` instance types serve the same goal: dereference to a register block. It …
> Send RAL instances

- imxrt-hal/src/dma.rs
I intended to mark these as `Send` in #49, but I missed it! This PR marks DMA channels as `Send` so they may be used wherever `Send` things are needed, like `Mutex`es.
Will be part of #59.
> Mark DMA channels as sendable

- imxrt-ral/imxrtral.py
Trying to squeeze in one more change before the release (#59)! If accepted, this change requires a re-build of the RAL.
I came upon this when I was writing automated unit tests for the [imxrt-uart-log](https://github.com/imxrt-rs/imxrt-uart-log) logging crate. I want to run 'cargo test' on my mac to run unit and doc tests. But, I hit an error:
```
LLVM ERROR: Global variable '__INTERRUPTS' has an invalid section
specifier '.vector_table.interrupts': mach-o section specifier
requires a segment whose length is between 1 and 16 characters.
```
Rather than always emitting the link section for `__INTERRUPTS`, we conditionally emit the link section when building for ARM targets. This lets me run unit tests on my host, while still including the link section for the targets that need it.
I've …
> Conditionally emit __INTERRUPT link section

- docs/RELEASE.md
- imxrt-hal/CHANGELOG.md
- imxrt-hal/Cargo.toml
- imxrt-ral/CHANGELOG.md
- imxrt-ral/imxrtral.py
All builds and publish dry-runs look OK at this point. I updated the release steps to better order the process.
I removed the `documentation` keys from both `Cargo.toml` files. Neither key pointed to a valid page on docs.rs, and it sounds like crates.io will [automatically provide the link](https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field) if we don't specify it.
Closes #59.
> Prepare 0.3.0 release of RAL and HAL

- .github/workflows/rust.yml
- CONTRIBUTING.md
- imxrt-ral/Makefile
The goal is to enable git dependencies and lower the bar for contribution. See #65 for more information.
The PR builds on #67. To ensure the checked-in RAL code is consistent with what is auto-generated, we add a new CI job, `gen-ral`, which will generate the RAL and check for any file differences. If users are correctly modifying the RAL by editing the `imxrtral.py` script, there should be no file differences between what is checked in and what is generated. But, if the user manually modifies a RAL source file, and it's not reflected in `imxrtral.py`, the job fails.
Note that this PR targets the `check-in-ral` branch, which is described by #67. If accepted, we should also feel comfortable accepting #67.
Testing
- I manually [made a RAL …
> Ensure checked-in RAL is consistent with generated RAL

- imxrt-hal/CHANGELOG.md
- imxrt-hal/src/lib.rs
- imxrt-ral/CHANGELOG.md
The PR adds a new function, `steal()`, to `Peripherals`. `steal()` lets users unsafely acquire all of the peripheral objects. It's unsafe, because the peripherals could be used elsewhere.
`steal()` is used by the RTIC framework to acquire device peripherals. The framework then hands-off the peripherals to the user, who can configure them and wrap them as additional (late) resources.
Users can `steal()` peripherals in non-RTIC applications. Note that `steal()` always returns the "uninitialized" types, which require additional setup to be useful. In that regard, it's a round-about, unsafe approach towards #20. However, as of this writing, there's no testing to see if re-initializing works for all peripherals.
> steal() peripherals; update changelog

- imxrt-hal/src/gpio.rs
We should read PSR when the GPIO is an input pin. When its an output
pin, and we want to know what state we're in, we should instead read
the data register.
Found by @mitchmindtree during teensy4-rs prototyping. Mitch found
that is_set_high() always returned `false`, even when we could see
that the GPIO was high. I also reproduced this in the teensy4-rs'
USB example, printing the state of the LED. Reading the DR register
resolved the issue in my testing.
> Fix StatefulOutputPin and read from data register

- imxrt-hal/CHANGELOG.md
- imxrt-hal/src/dma.rs
- imxrt-hal/src/dma/memcpy.rs
- imxrt-hal/src/dma/peripheral.rs
Queueing up additional, breaking HAL changes. This PR removes the `dma::{Config, ConfigBuilder}` types. Instead of providing separate values to describe interrupt on completion / half configuration, we set the configurations directly on a DMA `Channel`. The new approach lets us support interrupts when `Memcpy` operations complete. It also lets us track DMA channel configurations with the DMA channel itself, rather than having disparate types to maintain the settings.
> DMA: remove configuration types

- imxrt-hal/src/gpio.rs
- imxrt-hal/src/i2c.rs
- imxrt-hal/src/spi.rs
- imxrt-hal/src/uart.rs
- imxrt-iomuxc/src/config.rs
- imxrt-iomuxc/src/i2c.rs
- imxrt-iomuxc/src/lib.rs
- imxrt-iomuxc/src/pwm.rs
- imxrt-iomuxc/src/spi.rs
- imxrt-iomuxc/src/uart.rs
When we first proposed the iomuxc crate (#73), we said that most of the API was `unsafe`. We stressed the unsafety of functions like `set_sion()`, `configure()`, and `prepare()`, since the functions acted on types that were implemented *outside* of the crate, and we couldn't attest to their correctness.
In #75, we moved to a single crate with feature-flags implementation. Now that all pads are implemented in the same crate, we can easily check correctness of the implementations. The PR marks the pin preparation and pad configuration & muxing functions as safe.
It it still unsafe to generate the pad objects. But, as long as an interface guarantees only one live instance of a pad, everything should be sound. Let me know if we see any issues, or if we should keep these `unsafe`.
(In …
> Support a safer IOMUXC interface

- imxrt-ral/Cargo.toml
- imxrt-ral/imxrtral.py
According to [crates.io](https://crates.io/crates/imxrt-ral), the 0.3.0 version of the RAL is 6.11 MB. `cargo package --list` shows that we're packaging the SVD files and YAML patches. The SVD files are large, and they're not necessary for crate users.
The PR excludes the SVDs, and all contents not necessary for compiling the crate, from the packaged crate.
I'm not sure how to perfectly replicate the crates.io size calculation, but I can see a smaller `.crate` file on my system. Size of the `.crate` file before this change:
```
$ cargo package --manifest-path imxrt-ral/Cargo.toml --target thumbv7em-none-eabihf --features rt --features imxrt1062
$ gzip -l target/package/imxrt-ral-0.3.0.crate
compressed uncompressed  ratio uncompressed_name
4051368     86374400  95.3% …
```
> Exclude development files from RAL package

- docs/RELEASE.md
- imxrt-hal/CHANGELOG.md
- imxrt-hal/Cargo.toml
- imxrt-ral/CHANGELOG.md
- imxrt-ral/Cargo.toml
- imxrt-ral/imxrtral.py
The PR prepares a HAL and RAL 0.4 release. We also release 0.1 of the IOMUXC crates with this release.
> Release v0.4

- imxrt-iomuxc/Cargo.toml
- imxrt-iomuxc/src/lib.rs
- imxrt-iomuxc/tests/prelude.rs
The PR adds a small `prelude` module to the `imxrt-iomuxc` crate. `prelude` re-exports the general types and modules from the crate. It's to help HAL developers simply re-export the `imxrt-iomuxc` crate API without exposing the processor-specific IOMUXC module.
Today's usage in the HAL
https://github.com/imxrt-rs/imxrt-rs/blob/bd1b2df5afae5694ba71f33bc85e8fd349e358e7/imxrt-hal/src/lib.rs#L16-L27
produces [this API](https://docs.rs/imxrt-hal/0.4.0/imxrt_hal/iomuxc/index.html). The first `pub use imxrt_iomuxc::*;` statement includes a re-export of the `imxrt106x` module. We then re-export that module's interface through `pub use imxrt_iomuxc::imxrt106x::*;`. The end result is that the processor-specific types are reachable through the HAL's `iomuxc` module, and also the HAL's …
> IOMUXC prelude

- imxrt-hal/CHANGELOG.md
- imxrt-hal/src/gpio.rs
The PR addresses an inconsistency when enabling / disabling GPIO fast mode. If the fix looks good, I'll prepare a 0.4.1 patch release of the HAL.
There are two valid ways to prepare a high-speed GPIO output:
```rust
pub fn configure_led(pad: LedPadType) -> LED {
let mut led = hal::gpio::GPIO::new(pad);
led.set_fast(true);
led.output()
}
```
and
```rust
pub fn configure_led(pad: LedPadType) -> LED {
let mut led = hal::gpio::GPIO::new(pad).output();
led.set_fast(true);
led
}
```
the former will put the GPIO into high-speed, or 'fast,' mode before setting 'output mode.' The latter will put the GPIO into output mode before fast mode.
After transitioning into fast mode, the GPIO will start to reference a different GPIO register block. The issue is that, after entering fast mode, the output / …
> Maintain GPIO I/O configuration when enabling / disabling fast mode

- .gitignore
- imxrt-hal/src/lib.rs
- imxrt-hal/src/srtc.rs
This implements very basic support for the real-time clock: enabling the SRTC and RTC, setting the SRTC, and getting the current time.
The implementation is a bit awkward, but I'm not sure how to improve it; unlike the other peripherals I know of, the SRTC keeps running until it loses power or it is specifically disabled, so having two methods of enabling it (one that sets the time, one that does not) makes sense. I guess a builder pattern (like I2C) could be used, but not sure if it's worth it currently.
Also, setting the time while the RTC is running also makes sense, so that needs to be available while the RTC is running (and requires disabling it).
This implementation also takes ownership of the Secure Non-Volatile Storage instance, but the SNVS does a lot more than just the (S)RTC. …
> Implement basic support for the SRTC

- imxrt-iomuxc/Cargo.toml
- imxrt-iomuxc/README.md
- imxrt-iomuxc/build.rs
- imxrt-iomuxc/src/imxrt101x/mod.rs
- imxrt-iomuxc/src/imxrt101x/uart.rs
- imxrt-iomuxc/src/lib.rs
Adds the basic uart pin defs and beginnings of the imxrt101x iomux stuff to the repo
I ran into an annoyance in that the build (cargo build) in the project root fails in imxrt-hal if I don't specify imxrt1062 as default feature, I need to check the master branch again here first if that's how it was (been a bit since I did stuff!)
It's a nice feeling when you can git clone and cargo build though so maybe there's a nicer way of doing this or maybe this won't be an issue when I split the imxrt-hal stuff up more
> Imxrt101x iomuxc

- imxrt-hal/src/dma.rs
- imxrt-hal/src/dma/chip.rs
- imxrt-hal/src/dma/register.rs
The PR provides DMA support for all chip variants. DMA support is probably lower on #56's TODO list. However, the DMA implementation is more unique than the other peripherals: the RAL interface was hand-written. Hand-writing the RAL was necessary for providing a simpler API, since the `svd2ral` script generated a lot of symbols.
I arrived at this implementation by studying the reference manuals. In summary, the 1011 chip only has 16 DMA channels; chips that are 1015 and higher hav 32 DMA channels. When you have more than 16 DMA channels, you have the option for channel grouping. Today's DMA driver doesn't support channel grouping, so this is only a comment in the code.
The conditional compiles are hidden behind a new `chip` module, private to the DMA driver. We use the common symbols from …
> DMA support for all chip variants

- imxrt-iomuxc/src/imxrt101x/i2c.rs
- imxrt-iomuxc/src/imxrt101x/mod.rs
- imxrt-iomuxc/src/imxrt101x/spi.rs
The PR adds I2C and SPI `imxrt-iomuxc` trait implementations for the 1011 pads.
Part of #87.
> IOMUXC: Add I2C, SPI traits for 1011 pads

- imxrt1060-hal/src/i2c.rs
- imxrt1060-hal/src/spi.rs
These errors are only valid if the HAL is creating them, so don't allow users to create them. Pretty minor.
> Only allow HAL to create I2C/SPI config errors

- imxrt1060-hal/Cargo.toml
- imxrt1060-hal/src/lib.rs
- imxrt1060-hal/src/trng.rs
This adds support for the True Random Number Generator. It has a bunch of configurable things, few of which are safe to touch without reading the Security Reference Manual. The SRM requires a licensing agreement (and NDA) with NXP, so this is written with reference to the MCUXpresso SDK.
I think this driver should work for any i.MX chip other than the 1015 and 1021, which need `TRNG_ACC` in `MCTL` set to 1 after entering run mode. That field doesn't exist on other i.MX RT chips (it's `UNUSED5`). I think everything else is identical for the imxrt chips.
The output passes dieharder and practrand (out to 2GB, anyway). The TRNG is very slow and it took weeks to generate that much data.
This retrieves all 512 bits of entropy at once from the TRNG, rather than reading 32 bits at a time. This is …
> Implement basic support for the TRNG

- imxrt1060-hal/src/trng.rs
Woke up today and almost immediately realized that `0` is not inside the range `1..=15`. Woops.
I doubt this code change will actually matter, since users can't set a 0 retry count, but I didn't want to leave an incorrect comment laying around.
> Fix comment, don't preserve bad value in TRNG disable

- imxrt-hal/src/adc.rs
- imxrt-hal/src/dma/peripheral.rs
This commit makes the ADCs a possible source for DMA operations, and creates a
user-friendly wrapper class (StreamingAdc) which can abstract the necessary
buffer wrangling.
The StreamingAdc struct may not be a good fit for this crate (after making it, it seems to be a bit niche - supporting only the interrupts-with-256-element-double-buffers case), if so that's perfectly fine and I can pull it out. I might also be able to make it more better using some subset of:
* Const generics/genericize on buffer type
* Circular buffers
* Gracefully handle overflows
* Allow operation without an interrupt handler
But, it solves _my_ usecase, today at least, and that's the only important one, right? (and I didn't want to spend too much time on it without working toward some specific goal)
Also, this PR …
> Implement ADC DMA source and wrapper

- imxrt-hal/CHANGELOG.md
- imxrt-hal/Cargo.toml
- imxrt-hal/src/pwm.rs
This PR fixes a regression in the PWM driver, introduced in 0.4.0.
In the 0.3 HAL, we relied on the user to set the pin alternate
settings. But after introducing the IOMUXC crate in 0.4, we made pin
muxing part of the driver's responsibility, and added calls to prepare
pins. We missed the requirement in the PWM driver. This commit
corrects the PWM driver, which has been broken since the 0.4 release.
Tested in the teensy4-rs repo. Users who are not able to adopt the
next patch release could add equivalent iomuxc calls before
constructing their PWM driver.
> Fix PWM driver

- imxrt1060-hal/src/trng.rs
`rand_core` [requires that custom error codes start at `0xC000_0000`](https://docs.rs/rand_core/0.6.3/rand_core/struct.Error.html#associatedconstant.CUSTOM_START), which I missed when I wrote the impl
> Follow rand_core API

- imxrt-hal/CHANGELOG.md
- imxrt-hal/src/lib.rs
- imxrt-hal/src/tempmon.rs
I got a little bit side trapped by the *Temperature Monitor (TEMPMON)*
I thought it is barely simple and a great start in getting my hands dirty with the `imxrt-ral` ecosystem.
The interrupts are not really handy.
---
I played around with the UX a little bit and finally, it is OK. 
In my test app, I implemented a static alarm flag to note, when I have to enable the interrupts again.
Another method would be, to stop the measurement process, but as soon you read the temperature, the interrupt is triggered again. 
```rust
// skip rest
let mut t = peripherals.tempmon.init_with_measure_freq(0x100);
t.set_alarm_values(40.0, 70.0, 85.0);
let (low_alarm, high_alarm, panic_alarm) = t.alarm_values();
log::debug!("low {}, high {}, panic {}", low_alarm, high_alarm, panic_alarm);
// v2: AtomicBool …
```
> Add tempmon abstruction

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
- src/chip/imxrt10xx.rs
- src/chip/imxrt10xx/imxrt1020.rs
- src/lib.rs
Add chip configuration for the i.MX RT 1020 in accordance with the RM. Basic testing was done on EVK as well as an own design.
There is one TODO comment in here: In `imxrt1010.rs` `Clko2Selection` currently calls the`trace_clk_root` `TracClk` instead of `TraceClk`. I'm not sure if that is a typo or intentional. And regardless of whether it is how to spell it for 1020.
> Add 1020 chip configuration

- .github/workflows/rust.yml
- board/Cargo.toml
- board/README.md
- board/build.rs
- board/src/imxrt1060evk.rs
- board/src/lib.rs
All examples build. However, I'm not equipped with a 1060 EVK, so I haven't tested any of these on hardware.
Pinouts correspond to board revision A3. Looks like board revision B1 changes some header identifiers (J24 on A3 is J17 on B1, for example). I haven't done a diligent comparison to see if any pin routing is different.
Depends on imxrt-rs/imxrt-boot-gen#10. Once that's merged and released, I'll remove the git dependency here.
> Integrate i.MX RT 1060 EVK board for examples

- CHANGELOG.md
- board/src/imxrt1010evk.rs
- examples/rtic_gpio_input.rs
- src/chip/imxrt10xx/imxrt1010.rs
- src/common/timer.rs
- tests/1010_trace_clk_rename.rs
The PR fixes typos in the public API, and rename select `timer` types and methods. We maintain the misspelled / original APIs with deprecation warnings. See the individual commit messages for details.
I plan to release this in the 0.5 series. If accepted, I'll float the breaking removal commit(s) in a separate branch, and merge them once there's a more interesting breaking change to release.
> Deprecate and rename 0.5 APIs

- logging/CHANGELOG.md
- logging/src/usbd.rs
If we don't read data that the hosts sends us, we buffer the data and NAK the host.  The host might not like that. This commit resolves USB device logging issues observed on a Linux host. See here [1] for the troubleshooting and discussions.
[1]: https://github.com/mciantyre/teensy4-rs/discussions/132
Just by attempting to read, we mark the transfer as complete on our end. The driver doesn't attempt to copy anything, and it'll effectively discard the data by scheduling another transfer over whatever we received.
> Read the OUT endpoint in the USB device logger

- .github/workflows/rust.yml
- Cargo.toml
- board/build.rs
- board/src/lib.rs
- examples/rtic_usb_keypress.rs
- examples/rtic_usb_mouse.rs
- examples/rtic_usb_serial.rs
- examples/rtic_usb_test_class.rs
Recent USB troubleshooting ([here](https://github.com/mciantyre/teensy4-rs/discussions/132) and [here](https://github.com/imxrt-rs/imxrt-usbd/pull/21)) had me wanting USB examples on easily debug-able boards. The examples maintained in the imxrt-usbd repository only work on the Teensy 4, and there's no straightforward way to add new board support. Since imxrt-hal exports imxrt-usbd, I figure we could demonstrate the driver here, then receive the cross-board testing for free.
This PR ports the four primary USB examples from the imxrt-usbd repository. It rewrites them all to use RTIC. I tested them across my three available boards (Teensy 4, 1010EVK, 1170EVK) in various build and release configurations. The test-class and serial examples worked as expected against my macOS and Linux (RPi) …
> Port imxrt-usbd examples for cross-board USB testing

- .cargo/config.toml
- Cargo.toml
- board/Cargo.toml
- board/build.rs
- board/src/imxrt1010evk.rs
- board/src/imxrt1060evk.rs
- board/src/imxrt1170evk-cm7.rs
- board/src/lib.rs
- examples/rtic_defmt_rtt.rs
- logging/Cargo.toml
- logging/src/log.rs
The evk boards have a built in debug probe. When running firmware with probe-rs defmt-rtt provides a very fast channel of low cost debug println's that everyone finds really helpful.
Using panic-probe with defmt-rtt has a second benefit in allowing for programs to inform probe-rs the firmware has exited cleanly. This can be used for writing samples and tests that exit.
This also makes the imxrt-log defmt feature optional to the boards otherwise the two implementations of the defmt logger cause duplicate symbols to show up.
> Use defmt-rtt and panic-probe for evk boards

- src/chip/imxrt10xx.rs
- src/chip/imxrt10xx/ccm.rs
- src/chip/imxrt10xx/imxrt1010.rs
- src/chip/imxrt10xx/imxrt1020.rs
- src/chip/imxrt10xx/imxrt1060.rs
This adds support for setting source clock and dividers for FlexIO clock roots in accordance with the RMs
This is WIP because I haven't gotten around to testing the current version on actual hardware yet, but I'd like feedback on the general approach.
The issue here is that FLEXIO1_CLK_ROOT on 1010/1020 is FLEXIO2_CLK_ROOT on 106x, so there is some magic involved in getting the module names and doc comments right. Due to this it might also make sense to move this into a separate module and re-export it.
> Add 10xx FlexIO CCM configuration

- logging/src/defmt.rs
- logging/src/lib.rs
- logging/src/log/frontend.rs
- logging/src/lpuart.rs
- logging/src/usbd.rs
- src/common/pit.rs
- src/lib.rs
The [2024 edition](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/index.html) enables `unsafe_op_in_unsafe_fn` by default. This PR adds `unsafe` blocks and safety considerations throughout HAL and logging packages. There shouldn't be any functional changes.
Today's stable toolchain (1.77) also warns about the explicit references to `static mut`s. I'm taking the simple approach to resolve this eventual hard error.
Tested on an 1170EVK using the `rtic_logging` example, with both backends and both frontends.
> Eagerly address select Rust 2024 edition changes

- CHANGELOG.md
- examples/rtic_spi.rs
- src/common/lpspi.rs
These are most of the non-breaking changes proposed in #149. I extracted them so that we could test and release them with today's driver. Unless there's concern, I plan to publish these within the 0.5 releases.
> Add non-breaking LPSPI rework

- board/build.rs
- build.rs
- src/common/lpuart.rs
Future Rust toolchains will warn about unknown cfgs and introduce more clippy warnings. This PR eagerly fixes those warnings. See commits for more information.
> Fix warnings detected in upcoming toolchains

- logging/CHANGELOG.md
- logging/build.rs
- logging/src/lib.rs
[Community troubleshooting on Windows](https://github.com/mciantyre/teensy4-rs/issues/126) revealed that the USB device must use a bulk endpoint max packet size (MPS) of 512 bytes if the device is high speed. Since imxrt-log's USB back-end is already high-speed by default, this commit increases the default MPS to 512 bytes.
Tested using the rtic_logging and hal_logging examples on a Teensy 4. I've not tested against a Windows host, which is where this issue manifested.
> Increase imxrt-log default bulk MPS to 512

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
- board/src/imxrt1010evk.rs
- board/src/imxrt1060evk.rs
- board/src/imxrt1170evk-cm7.rs
- board/src/teensy4.rs
- examples/rtic_spi_controller.rs
- examples/rtic_spi_peripheral.rs
- src/common/lpspi.rs
Use `set_peripheral_enable` to transition the LPSPI driver from a controller into a peripheral. You can then use the lower-level LPSPI interface to coordinate I/O.
The PR includes two examples that you can run on physically-connected boards. See the example documentation for more info. I tested the LPSPI device behavior by running the `_peripheral` example on a 1010EVK and the `_controller` example on a 1170EVK. I'm eagerly updating the pin configurations for other boards.
Inspired by discussions [here](https://github.com/mciantyre/teensy4-rs/discussions/157).
> Demonstrate basic LPSPI peripheral functions

- Cargo.toml
- examples/rtic_defmt_rtt.rs
- examples/rtic_dma_uart.rs
- examples/rtic_gpio_input.rs
- examples/rtic_gpt.rs
- examples/rtic_logging.rs
- examples/rtic_pit.rs
- examples/rtic_pwm.rs
- examples/rtic_spi.rs
- examples/rtic_spi_blocking.rs
- examples/rtic_spi_controller.rs
- examples/rtic_spi_peripheral.rs
- examples/rtic_uart.rs
- examples/rtic_usb_keypress.rs
- examples/rtic_usb_mouse.rs
- examples/rtic_usb_serial.rs
- examples/rtic_usb_test_class.rs
The new framework has support for async tasks. It might be helpful for demonstrating async drivers, or for users who are comparing RTIC's latest documentation against our examples.
This is a minimal migration, and it's not trying to change any example's behavior. Let me know if you notice something different.
Tested on a 1010EVK using the `_pit`, `_defmt_rtt`, and `_logging` examples.  Also tested `_rtic_controller` on an 1170EVK, and `_rtic_peripheral` on a 1010EVK.
> Update examples to RTIC v2

- src/common/lpspi.rs
I introduced these in #157 but didn't use them. The unused warnings appear in the beta Clippy release. This PR eagerly fixes Clippy warning that might soon appear in stable.
> Remove LPSPI prototyping leftovers

- .github/workflows/rust.yml
- examples/rtic_spi.rs
It seems easy enough to use `rustup` and `cargo` directly. As of this PR, CI will promote clippy warnings in examples.
> Remove actions-rs from CI

- Cargo.toml
- Update `embedded-hal` to `0.2.6`:
This crate uses `eh02::blocking::i2c::Operation`, which only exists for `embedded-hal 0.2.6` and upwards
- Update `bitflags` to `1.3`:
This crate uses `.complement()` which only exists in `bitflags 1.3` and upwards
- Update `ral-registers` to `0.1.2`:
This crate uses newer features from `ral-registers 0.1.2`
> Fix embedded-hal version

- CHANGELOG.md
- board/src/teensy4.rs
- examples/hal_i2c_mpu9250.rs
- src/common/lpi2c.rs
Wait for the controller to become idle before returning to the transaction caller. This is a stronger guarantee than waiting until the stop bit is sent, and it meets the EH1 interface requirements.
This commit still keeps the busy check at the start of the transactions. If the bus is busy due to another controller's activity, I don't think we should block the caller while the other controller uses the bus. The caller can implement a retry policy given the characteristics of their system. EH1 lets users handle this condition with a dedicated error kind.
Additionally, this commit keeps the FIFO flushes at the start of transactions, after the busy checks. This is intended to avoid surprises in case a user inserts a high-level transaction somewhere in their low-level command sequence.
I …
> Block at end of LPI2C embedded-hal transactions

- Cargo.toml
Our usbd-hid 0.6 development dependency no longer builds. See the upstream [issue tracker](https://github.com/twitchyliquid64/usbd-hid/issues/72) for details. This [affects](https://github.com/imxrt-rs/imxrt-hal/actions/runs/9957883319/job/27510926864#step:4:160) the USB HID examples we maintain in this repository.
This commit patches the development dependency so our examples still build. Note that this only affects examples tied to imxrt-hal 0.5; see #168 for a breaking change that also fixes the build.
> Patch usbd-hid-macros development dependency

- CHANGELOG.md
- Cargo.toml
- board/Cargo.toml
- board/build.rs
- examples/rtic_usb_keypress.rs
- examples/rtic_usb_mouse.rs
- examples/rtic_usb_serial.rs
- examples/rtic_usb_test_class.rs
- logging/CHANGELOG.md
- logging/Cargo.toml
- logging/src/usbd.rs
The update requires us to adopt usb-device 0.3 and its associated dependencies. All USB examples, including rtic_logging, worked as expected on a Teensy 4.0. We're still passing the usb-device TestClass test suite on both a Teensy 4 and a 1010EVK.
> Update to imxrt-usbd 0.3

- src/common/lpuart.rs
From my understanding of the common::lpaurt::Baud::compute function, it is meant to test every oversampling rate from 8 to 32, and every modulo divisor from 1 to 8191.
The current code does not reset the modulo divisor value after comparing to an oversampling rate, leading to only one oversampling rate being tested. I've added a test that fails on the current code, but passes in the fixed code, highlighting the issue.
On a separate note, the oversampling rate is tested from 8 to 32, yet the minimum possible value is 4. I suspect that the author of the code found that sampling on both edges of the clock was unstable, or unfavorable for some reason, as this applies at oversampling rates <8. However, starting at the value of 8 limits possible baud rates to a maximum of 3MBd, while I've found …
> Lpuart Baud Compute Bug

- logging/src/defmt.rs
- logging/src/lib.rs
- src/chip/dma.rs
- src/chip/imxrt10xx/tempmon.rs
- src/common/flexpwm/ral.rs
- src/common/lpspi.rs
- src/common/pit.rs
- src/lib.rs
The PR adds safety notes to all `unsafe` blocks within the HAL and logging package. The PR also ensures that any unsafe public interface is also documented. See commit messages for details.
> Document unsafe interfaces, implementations

- CHANGELOG.md
- examples/rtic_spi_blocking.rs
- src/common/lpspi.rs
LPSPI receive operations are reversing byte and half-word elements when they place data in the caller's buffer. We can show this using the revised loopback tests on an older LPSPI driver.
The unpacking routines need to consider the frame boundary and the bit order when they deconstruct the 32 bit LPSPI word.
> Fix LPSPI word unpacking in receive operations

- src/chip/imxrt10xx/tempmon.rs
This makes it ergonomic to use tempmon in places that might panic, like `imxrt_temperature_task::spawn(tempmon).unwrap();`
> impl Debug for TempMon

- CHANGELOG.md
- Cargo.toml
- logging/CHANGELOG.md
- logging/Cargo.toml
Eagerly prepare for updates to our first-party dependencies:
- imxrt-rs/imxrt-ral#53
- imxrt-rs/imxrt-iomuxc#47
The patches effectively target those two PRs.
> Update imxrt dependencies, package versions

- .github/workflows/rust.yml
- CHANGELOG.md
- board/src/imxrt1010evk.rs
- board/src/imxrt1060evk.rs
- board/src/imxrt1170evk-cm7.rs
- board/src/teensy4.rs
- src/chip/drivers/dma.rs
- src/common/lpspi.rs
Most of these commits support a larger change that implements embedded-hal `SpiBus` and `SpiDevice` (#181). They also anticipate support for the 1180. See commit messages for details.
Although some of these may be backwards compatible, I'm not immediately back-porting them onto v0.5. Let me know if something seems useful.
Closes #131, since it provides a way to select and change the LPSPI hardware chip select. Also closes #149; this PR has a similar breaking change.
> Remove LPSPI chip select type state, and other refactors

- .github/workflows/rust.yml
In a previous commit (aa57636), I didn't include coverage for a chip build of imxrt-hal without defmt. This introduces the missing coverage.
> Lint imxrt-hal without defmt in CI

- .github/workflows/rust.yml
- Cargo.toml
- board/Cargo.toml
- board/build.rs
- board/src/imxrt1010evk.rs
- board/src/lib.rs
- board/src/teensy4.rs
- examples/rtic_sai_pcm5102.rs
- examples/rtic_sai_wm8960.rs
- src/chip/drivers/ccm_10xx/analog.rs
- src/chip/drivers/sai.rs
- src/chip/imxrt1010.rs
- src/chip/imxrt1020.rs
- src/chip/imxrt1060.rs
- src/chip/imxrt1170.rs
I try to pick up the work on the SAI driver, started in https://github.com/imxrt-rs/imxrt-hal/pull/143
Updates:
* Rebased
* Added Teensy4 support with SAI1
The implementation is still Tx only, with 1010evk and Teensy board support only (I tested only on Teensy). Rx functionality is incomplete. I plan to work on it next, but I would like to first kick off the review of the current content.
Thanks in advance!
> SAI driver rebased + Teensy support.

- Cargo.toml
- examples/hal_clock_out.rs
- examples/rtic_sai_pcm5102.rs
- examples/rtic_sai_sgtl5000.rs
- examples/rtic_usb_keypress.rs
- examples/rtic_usb_serial.rs
- src/chip/drivers/sai.rs
Exposed sai config properties as public, so the user can update before split().
rtic_sai_pcm5102 example enables the Rx+Tx clock in sync, so Tx data works with Rx clock (e.g. to match Teensy audio board pinout).
> Sai RX implementation and Teensy audio board example

- CHANGELOG.md
- board/src/imxrt1010evk.rs
- board/src/teensy4.rs
- src/chip/drivers/sai.rs
This came up in the first review, but it was missed in subsequent reviews. See the changelog for more information.
Users can configure their clocks themselves. I'm treating this as a driver bug, and I'll release an updated driver in the 0.5 series.
> Remove IOMUXC_GPR writes in SAI driver
